name: Latest blog post workflow
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://bs-studio.fr/rss.xml"
          max_post_count: 2
          template: "<td width=\"50%\" valign=\"top\"><h3>$title</h3><p>$description</p><a href=\"$url\">Lire l'article →</a></td>"
